# Generated by Django 3.0.4 on 2020-03-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20200329_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='passwaord',
            new_name='password',
        ),
    ]
